### PR TITLE
Refactor the module to work with Godot 3.0 alpha

### LINKED ISSUE #2: Compile Error with Godot 3 master
I get the following error when compiling opensimplex with Godot 3 master, both when compiling with with the voxel module and alone.

> In file included from modules/opensimplex/register_types.cpp:2:0:
> modules/opensimplex/noise.h:10:33: error: ISO C++ forbids declaration of 'OBJ_TYPE' with no type [-fpermissive]
>      OBJ_TYPE(OsnNoise, Reference)
>                                  ^
> 

Full pastebin of the errors: https://pastebin.com/HNXFSxwM

Googling the issue led me to this: https://github.com/khairul169/gdsqlite/issues/8
And so I am thinking it could be a problem on your end?

Thank you and I hope I can get your modules to work! They seem amazing!

### PR DESCRIPTION
**Pull request by Xrayez**
Made necessary changes to the module to compile it with Godot 3.0 alpha.

Fixes #2

This compiles successfully on my local machine with mingw cross-compilation for windows platform.

### CODE REVIEW

**Comment by HummusSamurai** [comment]
Thank you! 
I compiled it and it works!

But now I have another issue that I'll see if I can ask the devs about :b 
https://github.com/Zylann/godot_voxel/issues/12
